#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';
use autodie;
use Getopt::Std;
use File::Basename;
$Getopt::Std::STANDARD_HELP_VERSION = 1;

# get args
my %opts;
getopts('x:p:t:e:m:', \%opts);
for (qw( x p t e m )) {
    HELP_MESSAGE() unless $opts{$_};
}
sub HELP_MESSAGE {
    print <<EOF;
Usage: $0 -x XML -p PLATFORM -t TARGET -e EXPERIMENT -m MOM_VERSION
EOF
    exit 1;
}

# get the includeDir
my $command = "frelist -x $opts{x} -p $opts{p} -t $opts{t} $opts{e} -d include";
print "\n>>$command\n";
chomp (my $includeDir = `$command`);
die "Couldn't determine includeDir" unless $includeDir;
run("mkdir -p $includeDir") unless -d $includeDir;
die "Couldn't mkdir $includeDir" unless -d $includeDir;
#print "includeDir = $includeDir\n";

# get the xmlDir
my $xmlDir = dirname($opts{x});
die "Couldn't find awg_include in $xmlDir" unless -d "$xmlDir/awg_include";
#print "xmlDir = $xmlDir\n";

# copy awg_include
run("rsync -rLptgoD $xmlDir/awg_include/ $includeDir/awg");

# clone MOM examples
run("git clone -b dev/master/$opts{m} https://github.com/NOAA-GFDL/MOM6-examples.git $includeDir/mom6")
    unless -d "$includeDir/mom6";

print "\nSuccessfully filled includeDir = $includeDir\n";

sub run {
    my $command = shift;
    print "\n>>$command\n";
    system $command and die "$command failed to run";
}
