#!/usr/bin/perl

while (<>) {
    if (/atmos_station_001/ and ! /^\s*#/) {
        for my $i (1 .. 121) {
            $i = 0 . $i until length $i == 3;
            (my $line = $_) =~ s/atmos_station_001/atmos_station_$i/;
            print $line;
        }
    }
    else {
        print;
    }
}
